# Site settings
title: "Robocode Unipar 2014"
email: "robocodeunipar@gmail.com"
description: "Site da competição de Robocode na Unipar Campus Francisco Beltrão."
baseurl: ""
url: "http://robocodeunipar2014.github.io"
twitter_username: robocodeunipar
github_username:  robocodeunipar2014

# Build settings
markdown: kramdown
permalink: pretty
